# set default handlers from settings file (plist and simple settings files)
# ❯ duti -v ~/.config/duti.conf

# Alternately: set default handlers from setting folder (plist and simple settings files)
# ❯ duti -v ~/.config/duti/


# blank lines and lines beginning with a '#' are ignored
#
# Valid roles are defined as follows:
# all         application handles all roles for the given UTI.
# viewer      application handles reading and displaying documents with the given UTI.
# editor      application can manipulate and save the item. Implies viewer.
# shell       application can execute the item.
# none        application cannot open the item, but provides an icon for the given UTI.

# app bundle id                 UTI/ext/MIME type               role
com.VortexApps.NZBVortex3       dyn.ah62d4rv4ge8068xc           all
com.VortexApps.NZBVortex3       nzb                             all
com.colliderli.iina             mkv                             viewer
com.colliderli.iina             avi                             viewer
com.colliderli.iina             mp4                             viewer
com.microsoft.VSCode            py                              all


# Display information about the default application for a given extension:
# ❯ duti -x ext

# Display the default handler for a given UTI:
# ❯ duti -d uti

# Display all handlers of a given UTI:
# ❯ duti -l uti 
